"""empty message

Revision ID: 3cf7277a756c
Revises: 736005194cfb
Create Date: 2020-03-17 18:42:01.811047

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '3cf7277a756c'
down_revision = '736005194cfb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('department', sa.Column('manager_id', sa.String(length=6), nullable=True))
    op.add_column('leave', sa.Column('addtime', sa.DateTime(), nullable=True))
    op.add_column('leave', sa.Column('manager_id', sa.String(length=6), nullable=True))
    op.drop_column('leave', 'manger_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('leave', sa.Column('manger_id', mysql.VARCHAR(length=6), nullable=True))
    op.drop_column('leave', 'manager_id')
    op.drop_column('leave', 'addtime')
    op.drop_column('department', 'manager_id')
    # ### end Alembic commands ###
