"""empty message

Revision ID: 443a45aa0a97
Revises: 51b3977d631f
Create Date: 2020-03-18 17:41:03.651478

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '443a45aa0a97'
down_revision = '51b3977d631f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('attendance', sa.Column('month', sa.Integer(), nullable=True))
    op.drop_column('attendance', 'work_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('attendance', sa.Column('work_id', mysql.VARCHAR(length=6), nullable=True))
    op.drop_column('attendance', 'month')
    # ### end Alembic commands ###
