"""empty message

Revision ID: 52792cc1f5d4
Revises: bab90e93b06b
Create Date: 2020-03-21 21:40:30.712159

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '52792cc1f5d4'
down_revision = 'bab90e93b06b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('salary', sa.Column('real_salary', sa.DECIMAL(precision=10, scale=2), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('salary', 'real_salary')
    # ### end Alembic commands ###
