"""empty message

Revision ID: 695e2429bb1f
Revises: d3ea29fb7aee
Create Date: 2020-03-22 10:55:52.737333

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '695e2429bb1f'
down_revision = 'd3ea29fb7aee'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('salary',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('work_id', sa.String(length=6), nullable=True),
    sa.Column('base_salary', sa.Float(precision=10, asdecimal=2), nullable=True),
    sa.Column('grant', sa.Float(precision=10, asdecimal=2), nullable=True),
    sa.Column('insur_fund', sa.Float(precision=10, asdecimal=2), nullable=True),
    sa.Column('fine', sa.Float(precision=10, asdecimal=2), nullable=True),
    sa.Column('real_salary', sa.Float(precision=10, asdecimal=2), nullable=True),
    sa.Column('month', sa.String(length=6), nullable=True),
    sa.Column('addtime', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('salary')
    # ### end Alembic commands ###
