"""'attendance'

Revision ID: 6f917be835af
Revises: fd25eac312e7
Create Date: 2020-03-18 11:24:25.621875

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6f917be835af'
down_revision = 'fd25eac312e7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('attendance',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('work_id', sa.String(length=6), nullable=True),
    sa.Column('late_count', sa.Integer(), nullable=True),
    sa.Column('lvearly_count', sa.Integer(), nullable=True),
    sa.Column('work_hours', sa.Integer(), nullable=True),
    sa.Column('work_time', sa.DateTime(), nullable=True),
    sa.Column('leave_time', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('leave', sa.Column('vacat_time', sa.Integer(), nullable=True))
    op.add_column('sign', sa.Column('is_late', sa.Integer(), nullable=True))
    op.add_column('sign', sa.Column('is_lvearly', sa.Integer(), nullable=True))
    op.add_column('sign', sa.Column('outtime', sa.DateTime(), nullable=True))
    op.add_column('sign', sa.Column('signtime', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('sign', 'signtime')
    op.drop_column('sign', 'outtime')
    op.drop_column('sign', 'is_lvearly')
    op.drop_column('sign', 'is_late')
    op.drop_column('leave', 'vacat_time')
    op.drop_table('attendance')
    # ### end Alembic commands ###
