"""'leave'

Revision ID: 736005194cfb
Revises: f118f53d218d
Create Date: 2020-03-16 20:53:31.792782

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '736005194cfb'
down_revision = 'f118f53d218d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('leave',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('work_id', sa.String(length=6), nullable=True),
    sa.Column('manger_id', sa.String(length=6), nullable=True),
    sa.Column('reason', sa.Text(), nullable=True),
    sa.Column('is_agree', sa.Boolean(), nullable=True),
    sa.Column('status', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('leave')
    # ### end Alembic commands ###
