"""empty message

Revision ID: 78f141f7ecd6
Revises: e0abcae76325
Create Date: 2020-03-17 20:27:25.658335

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '78f141f7ecd6'
down_revision = 'e0abcae76325'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('leave', sa.Column('leave_name', sa.String(length=30), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('leave', 'leave_name')
    # ### end Alembic commands ###
