"""'employee'

Revision ID: 900f84ca2e41
Revises: f18beda458df
Create Date: 2020-03-13 10:44:06.123405

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '900f84ca2e41'
down_revision = 'f18beda458df'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('employee', sa.Column('address', sa.String(length=100), nullable=True))
    op.add_column('employee', sa.Column('age', sa.Integer(), nullable=True))
    op.add_column('employee', sa.Column('depart', sa.String(length=100), nullable=True))
    op.add_column('employee', sa.Column('email', sa.String(length=100), nullable=True))
    op.add_column('employee', sa.Column('id_card', sa.Integer(), nullable=True))
    op.add_column('employee', sa.Column('phone', sa.String(length=11), nullable=True))
    op.add_column('employee', sa.Column('post', sa.String(length=100), nullable=True))
    op.add_column('employee', sa.Column('sex', sa.Boolean(), nullable=True))
    op.add_column('employee', sa.Column('work_num', sa.String(length=6), nullable=True))
    op.create_unique_constraint(None, 'employee', ['email'])
    op.create_unique_constraint(None, 'employee', ['phone'])
    op.create_unique_constraint(None, 'employee', ['id_card'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'employee', type_='unique')
    op.drop_constraint(None, 'employee', type_='unique')
    op.drop_constraint(None, 'employee', type_='unique')
    op.drop_column('employee', 'work_num')
    op.drop_column('employee', 'sex')
    op.drop_column('employee', 'post')
    op.drop_column('employee', 'phone')
    op.drop_column('employee', 'id_card')
    op.drop_column('employee', 'email')
    op.drop_column('employee', 'depart')
    op.drop_column('employee', 'age')
    op.drop_column('employee', 'address')
    # ### end Alembic commands ###
