"""'salary'

Revision ID: bab90e93b06b
Revises: 443a45aa0a97
Create Date: 2020-03-21 20:38:35.874981

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bab90e93b06b'
down_revision = '443a45aa0a97'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('salary',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('work_id', sa.String(length=6), nullable=True),
    sa.Column('base_wage', sa.DECIMAL(precision=10, scale=2), nullable=True),
    sa.Column('grant', sa.DECIMAL(precision=10, scale=2), nullable=True),
    sa.Column('insur_fund', sa.DECIMAL(precision=10, scale=2), nullable=True),
    sa.Column('fine', sa.DECIMAL(precision=10, scale=2), nullable=True),
    sa.Column('addtime', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('salary')
    # ### end Alembic commands ###
