"""empty message

Revision ID: d3ea29fb7aee
Revises: 6349380e7018
Create Date: 2020-03-21 22:06:51.075141

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd3ea29fb7aee'
down_revision = '6349380e7018'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('salary', sa.Column('month', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('salary', 'month')
    # ### end Alembic commands ###
