"""empty message

Revision ID: e0abcae76325
Revises: 3cf7277a756c
Create Date: 2020-03-17 19:06:00.767389

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'e0abcae76325'
down_revision = '3cf7277a756c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('leave', sa.Column('addtime', sa.DateTime(), nullable=True))
    op.add_column('leave', sa.Column('manager_id', sa.String(length=6), nullable=True))
    op.drop_column('leave', 'manger_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('leave', sa.Column('manger_id', mysql.VARCHAR(length=6), nullable=True))
    op.drop_column('leave', 'manager_id')
    op.drop_column('leave', 'addtime')
    # ### end Alembic commands ###
