"""'sign'

Revision ID: ed7a0c0ff82b
Revises: d6c756737ca7
Create Date: 2020-03-16 16:06:39.439539

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ed7a0c0ff82b'
down_revision = 'd6c756737ca7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('sign',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('work_id', sa.String(length=6), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('sign')
    # ### end Alembic commands ###
