"""empty message

Revision ID: f18beda458df
Revises: f01c1c5dd17b
Create Date: 2020-03-12 12:03:04.093015

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f18beda458df'
down_revision = 'f01c1c5dd17b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('employee', sa.Column('addtime', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('employee', 'addtime')
    # ### end Alembic commands ###
