# Generated by Django 2.1 on 2019-09-25 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=50)),
                ('password', models.CharField(max_length=100)),
                ('status', models.IntegerField(default=0)),
                ('phone', models.CharField(max_length=11)),
                ('sex', models.CharField(max_length=1)),
                ('age', models.CharField(max_length=3)),
                ('pic_url', models.CharField(max_length=100)),
                ('addtime', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
