# Generated by Django 2.1 on 2019-09-26 19:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myadmin', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cates',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('upid', models.IntegerField()),
                ('paths', models.CharField(max_length=50)),
            ],
        ),
    ]
