# Generated by Django 2.1 on 2019-09-29 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myadmin', '0004_auto_20190929_1152'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='pic_url',
            field=models.CharField(default='/static/pics/default.png', max_length=100),
        ),
    ]
