# Generated by Django 2.1 on 2019-10-09 19:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myadmin', '0006_auto_20190929_1450'),
    ]

    operations = [
        migrations.CreateModel(
            name='Carts',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cdprice', models.IntegerField(default=0)),
                ('cprice', models.IntegerField(default=0)),
                ('csprice', models.IntegerField(default=0)),
                ('cgoods_name', models.CharField(max_length=50)),
                ('cgoods_pic', models.CharField(max_length=50)),
                ('cgid', models.IntegerField(default=0)),
                ('num', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_id', models.IntegerField(default=1570620292)),
                ('ostatus', models.IntegerField(default=0)),
                ('oprice', models.IntegerField(default=1)),
                ('addtime', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
