# Generated by Django 2.1 on 2019-10-09 20:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myadmin', '0007_carts_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carts',
            name='cgid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myadmin.Goods'),
        ),
        migrations.AlterField(
            model_name='order',
            name='order_id',
            field=models.IntegerField(default=1570624774),
        ),
    ]
