# Generated by Django 2.1 on 2019-10-11 21:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myadmin', '0012_auto_20191011_2037'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='addtime',
            new_name='createtime',
        ),
        migrations.RenameField(
            model_name='order',
            old_name='ostatus',
            new_name='status',
        ),
        migrations.RemoveField(
            model_name='order',
            name='oprice',
        ),
        migrations.RemoveField(
            model_name='order',
            name='order_id',
        ),
        migrations.AddField(
            model_name='order',
            name='addinfo',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='order',
            name='name',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='order',
            name='pay',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='order',
            name='paytime',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='phone',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='order',
            name='total',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='order',
            name='uid',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='myadmin.Users'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='order',
            name='wl',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
